# name: Daily Subscription Scan

# on:
#   schedule:
#     - cron: '0 0 * * *'
#   workflow_dispatch:

# jobs:
#   scan-subscriptions:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout Repository
#       uses: actions/checkout@v2

#     - name: Azure Login action
#       uses: azure/login@v2
#       with:
#         creds: ${{ secrets.AZURE_CREDENTIALS }}
#         enable-AzPSSession: true
#         allow-no-subscriptions: true

#     # - name: Run Subscription Scan Script
#     #   uses: azure/powershell@v2
#     #   run: |
#     #     pwsh -f ./scripts/subscription_scan.ps1
#       # env:
#       #   AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
#       #   AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
#       #   AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
#       #   AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
#       #   AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
#     - name: Run Azure PowerShell Script File
#       uses: azure/powershell@v2
#       with:
#         inlineScript: ./scripts/subscription_scan.ps1
#         azPSVersion: "latest"
#       env:
#         AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
#         AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}

#     - name: Send Teams Notification
#       if: success() && steps.new-subscriptions.outputs.new_subscriptions == 'true'
#       run: |
#         curl -H 'Content-Type: application/json' \
#         -d '{"text": "New Azure Subscriptions Found. Check the latest scan results."}' \
#         ${{ secrets.TEAMS_WEBHOOK_URL }}
#       env:
#         TEAM_WEBHOOK_URL: ${{ secrets.TEAM_WEBHOOK_URL }}


name: Daily Subscription Scan

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Manual trigger option

jobs:
  scan-subscriptions:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Azure Login action
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
        allow-no-subscriptions: true

    - name: Run Azure PowerShell Script File
      uses: azure/powershell@v2
      with:
        inlineScript: ./scripts/subscription_scan.ps1
        azPSVersion: "latest"
      env:
        AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
        AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
        TEAM_WEBHOOK_URL: ${{ secrets.TEAM_WEBHOOK_URL }}  # Added Teams webhook URL
